# リリースノート設定ファイル
changelog:
  # カテゴリ設定。変更項目をカテゴリ分けする
  categories: 
    - title: Enhancemnet
      labels:
        # "Enhancement"へ掲載するプルリクエストのラベル
        - enhancement
    - title: Bug Fixes
      labels:
        # "Bug Fixes"へ掲載するプルリクエストのラベル
        - bug
        - fixes
  exclude:
    # リリースノートに掲載しないプルリクエストのラベル
    labels:
      - dependencies
    # 下記のユーザーのプルリクエストをリリースノートに掲載しない
    authors:
      - dependabot