name: Test
on:
    pull_request:   # Run on pull requests
        paths: ['go/**/*.go']   # Run only on changes to go files
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4 # Checkout the code
            - uses: actions/setup-go@v5 # Set up Go
              with:
                  go-version-file: .go-version
            - run: go test go/excellent/*.go # Run the testsi